//
//  SkinLogPDFExporter.swift
//  AAINA
//

import UIKit

enum SkinLogPDFExporter {

    static func generate(from entry: SkinLogEntry) -> URL {
        let pageWidth:  CGFloat = 595   // A4 pt width
        let pageHeight: CGFloat = 842
        let margin:     CGFloat = 48

        let fmt = DateFormatter()
        fmt.dateStyle = .long
        fmt.timeStyle = .short
        let dateString = fmt.string(from: entry.date)

        // Compose filename
        let ts    = Int(entry.date.timeIntervalSince1970)
        let fname = "SkinLog_\(ts).pdf"
        let url   = FileManager.default.temporaryDirectory.appendingPathComponent(fname)

        let renderer = UIGraphicsPDFRenderer(bounds: CGRect(x: 0, y: 0, width: pageWidth, height: pageHeight))

        let data = renderer.pdfData { ctx in
            ctx.beginPage()
            var y: CGFloat = margin

            // ── Header bar ───────────────────────────────────────────────
            let headerRect = CGRect(x: 0, y: 0, width: pageWidth, height: 70)
            UIColor(red: 0.91, green: 0.62, blue: 0.62, alpha: 1).setFill()
            UIRectFill(headerRect)

            let titleAttrs: [NSAttributedString.Key: Any] = [
                .font: UIFont.systemFont(ofSize: 22, weight: .bold),
                .foregroundColor: UIColor.white
            ]
            "Skin Log Report".draw(at: CGPoint(x: margin, y: 22), withAttributes: titleAttrs)
            y = 90

            // ── Date ─────────────────────────────────────────────────────
            draw(label: "Date", value: dateString, x: margin, y: &y, pageWidth: pageWidth, margin: margin)

            // ── Flare-up status ───────────────────────────────────────────
            let flareValue = entry.isFlareUp ? "Yes" : "No"
            draw(label: "Flare-up", value: flareValue, x: margin, y: &y, pageWidth: pageWidth, margin: margin)

            // ── Skin concerns ─────────────────────────────────────────────
            if !entry.flareUps.isEmpty {
                draw(label: "Skin Concerns", value: entry.flareUps.joined(separator: ", "),
                     x: margin, y: &y, pageWidth: pageWidth, margin: margin)
            }

            // ── Notes ─────────────────────────────────────────────────────
            if !entry.note.isEmpty {
                y += 12
                drawSectionTitle("Notes", x: margin, y: &y)
                let noteAttrs: [NSAttributedString.Key: Any] = [
                    .font: UIFont.systemFont(ofSize: 13),
                    .foregroundColor: UIColor.darkGray
                ]
                let noteRect = CGRect(x: margin, y: y, width: pageWidth - margin * 2, height: 300)
                entry.note.draw(in: noteRect, withAttributes: noteAttrs)
                let noteHeight = entry.note.boundingRect(
                    with: CGSize(width: pageWidth - margin * 2, height: 300),
                    options: .usesLineFragmentOrigin,
                    attributes: noteAttrs,
                    context: nil
                ).height
                y += noteHeight + 16
            }

            // ── Photo count note ──────────────────────────────────────────
            if !entry.photoFileNames.isEmpty {
                y += 4
                draw(label: "Photos attached", value: "\(entry.photoFileNames.count)",
                     x: margin, y: &y, pageWidth: pageWidth, margin: margin)
            }

            // ── Footer ────────────────────────────────────────────────────
            let footerY: CGFloat = pageHeight - 40
            let footerAttrs: [NSAttributedString.Key: Any] = [
                .font: UIFont.systemFont(ofSize: 10),
                .foregroundColor: UIColor.lightGray
            ]
            "Generated by AAINA · \(dateString)".draw(at: CGPoint(x: margin, y: footerY), withAttributes: footerAttrs)
        }

        try? data.write(to: url)
        return url
    }

    // MARK: - Drawing helpers

    private static func draw(label: String, value: String,
                             x: CGFloat, y: inout CGFloat,
                             pageWidth: CGFloat, margin: CGFloat) {
        let labelAttrs: [NSAttributedString.Key: Any] = [
            .font: UIFont.systemFont(ofSize: 12, weight: .semibold),
            .foregroundColor: UIColor(red: 0.65, green: 0.35, blue: 0.45, alpha: 1)
        ]
        let valueAttrs: [NSAttributedString.Key: Any] = [
            .font: UIFont.systemFont(ofSize: 13),
            .foregroundColor: UIColor.darkText
        ]

        label.draw(at: CGPoint(x: x, y: y), withAttributes: labelAttrs)
        y += 18
        value.draw(at: CGPoint(x: x, y: y), withAttributes: valueAttrs)
        y += 22

        // Divider
        UIColor.lightGray.withAlphaComponent(0.3).setStroke()
        let path = UIBezierPath()
        path.move(to: CGPoint(x: x, y: y))
        path.addLine(to: CGPoint(x: pageWidth - margin, y: y))
        path.lineWidth = 0.5
        path.stroke()
        y += 16
    }

    private static func drawSectionTitle(_ title: String, x: CGFloat, y: inout CGFloat) {
        let attrs: [NSAttributedString.Key: Any] = [
            .font: UIFont.systemFont(ofSize: 12, weight: .semibold),
            .foregroundColor: UIColor(red: 0.65, green: 0.35, blue: 0.45, alpha: 1)
        ]
        title.draw(at: CGPoint(x: x, y: y), withAttributes: attrs)
        y += 20
    }
}
